### ISSUE TITLE
wp-redis error

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/wp_launch_check#11]
Reported by a customer:

launch check recommended I install wp-redis.  This is the message I get 
when I attempt to activate it.

Fatal error: Cannot redeclare class WP_Object_Cache in 
/srv/bindings/0fef773f42984256a4f6feec2556a5ed/code/wp-content/plugins/wp-redis/object-cache.php 
on line 262

**Comment by mikevanwinkle** [comment]
So I think the recommendation in our documentation is that they don't activate the plugin ... they have to move the object-cache.php from the plugin directory to wp-content/object-cache.php. See here: https://pantheon.io/docs/articles/sites/installing-redis-on-wordpress/

**Comment by bmackinney** [comment]
We'll modify (this line)[https://github.com/pantheon-systems/wp_launch_check/blob/master/php/pantheon/checks/objectcache.php#L34] to direct users towards that article. Thanks @mikevanwinkle!

**Comment by markjaquith** [comment]
Here's an idea. Move the WordPress plugin headers out of `object-cache.php` and into a `wp-redis.php` file. The `wp-redis.php` file should, on activation of itself:

1. Make sure Redis is available.
2. Make sure Redis is configured via `$_ENV` or `$redis_server`.
3. If 1 and 2 are met, it should see if there is already `WP_CONTENT_DIR . '/object-cache.php'`
4. If there is not an `WP_CONTENT_DIR . '/object-cache.php'`, it should copy its own `object-cache.php` in.
5. If it cannot copy its on `object-cache.php` in, it should tell the user to do so manually.
6. It should deactivate itself.

**Comment by danielbachhuber** [comment]
I've moved the plugin headers for WP Redis to a separate file, so it's harmless to activate.

**Comment by blueprintmrk** [comment]
Thank you!
