### ISSUE TITLE
InnoDB Issue

### ISSUE THREAD

**Issue by nataliejeremy** [pantheon-systems/wp_launch_check#12]
Reported by a customer:

Launch check flagged my tables as not using innoDB.  What problem does 
that cause?

**Comment by bmackinney** [comment]
We should edit the message this check produces by adding a link to a document explaining the virtues of innoDB, provide a short explanation, and add a colon after "to fix". The message code is located at [this line](https://github.com/pantheon-systems/wp_launch_check/blob/master/php/pantheon/checks/database.php#L86)

**Comment by joshkoenig** [comment]
Also, as pointed out in #16 - the recommended command doesn't work. For best service I think:

1. We need a better doc with adapted content from Cal's (Blog Post)[https://pantheon.io/blog/moving-mysql-tables-myisam-innodb]
2. We can add a terminus command to do this for people. ;)

**Comment by bmackinney** [comment]
@bensheldon ruled this out as a terminus command. We've created the doc and could replace [the message](https://github.com/pantheon-systems/wp_launch_check/blob/e7a861494a46af3195ecdcf5a1abba0a99fd3e68/php/pantheon/checks/database.php#L86) with a link to [the doc](https://pantheon.io/docs/articles/sites/database/myisam-to-innodb/)

**Comment by joshkoenig** [comment]
Closing in favor of #16
