### ISSUE TITLE
"SESSION" check is too broad. Picks up false positives.

### ISSUE THREAD

**Issue by markjaquith** [pantheon-systems/wp_launch_check#15]
The check for PHP session code is too broad. It appears to just check for the presence of "SESSION" anywhere. The WooCommerce plugin, for example, has a non-FS session handler. One of its comment blocks has the word "SESSION" in uppercase. Kinda funny that this gets flagged, as it is related to code that explicitly makes sessions usable in multi-server environments. :grin:

**Comment by joshkoenig** [comment]
Gonna make a new issue to now reference our plugin correctly. ;P

**Comment by westonruter** [comment]
See also the sniffs for PHP_CodeSniffer:

https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/VIP/SessionFunctionsUsageSniff.php
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/VIP/SessionVariableUsageSniff.php
