### ISSUE TITLE
Possibly integrate the detection of plugins that have known issues in Pantheon 

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/wp_launch_check#154]
One common gotchas of first time Pantheon users are plugins that needs workarounds in the platform like the ones highlighted here https://docs.pantheon.io/plugins-known-issues#assumed-write-access specially the ones that assumes write access, some non savvy GUI users are not comfortable with command line when setting it up and usually gives up, so possibly integrate the functionality of the plugin https://wordpress.org/plugins/easy-symlinks the mu plugins

**Comment by jazzsequence** [comment]
Migrated to `wp_launch_check` from `pantheon-mu-plugin`. Agree with @pwtyler's comment above, this is more a Status Check thing.

**Comment by pwtyler** [comment]
Despite the above conversation 1+ year ago, this was implemented in the mu after all.
https://github.com/pantheon-systems/pantheon-mu-plugin/pull/48
