### ISSUE TITLE
Check for hardcoded database credentials

### ISSUE THREAD

**Issue by markjaquith** [pantheon-systems/wp_launch_check#17]
When I was moving a site over to Pantheon, it had hardcoded database credentials, instead of using the ENV variables you provide. I figured it out eventually from the docs, but it would be nice if the preflight check looked to see if the user has hardcoded any `DB_*` values with strings in `wp-config.php`, and spat out the code they should be using instead.

**Comment by mikevanwinkle** [comment]
+1

**Comment by danielbachhuber** [comment]
We'll need to retool Launch Check a bit to accommodate this — namely, run the config check before WP is loaded, then load WP and run the rest of the checks.
