### ISSUE TITLE
Make sure WP_CACHE is not defined in wp-config.php

### ISSUE THREAD

**Issue by markjaquith** [pantheon-systems/wp_launch_check#23]
`WP_CACHE` is a constant used to attempt the loading of `wp-content/advanced-cache.php`, which is used for page caching plugins. These plugins shouldn't be running on Pantheon, and even if there isn't one installed, setting `WP_CACHE` causes WordPress to look for that file unnecessarily. Best to flag it and tell the user to eliminate it.

Implementation:

`define\s*?\(` and `WP_CACHE` on the same line in `wp-config.php`

**Comment by espellcaste** [comment]
+1
