### ISSUE TITLE
Keeping WP-CLI Fresh

### ISSUE THREAD

**Issue by nstielau** [pantheon-systems/wp_launch_check#29]
http://wp-cli.org/blog/version-0.18.0.html

We should get into a rhythm of keeping this up to date. We don't need to worry about legacy versions at this time.

**Comment by joshkoenig** [comment]
@danielbachhuber @greg-1-anderson - can I task the two of you with discussion a process for keeping our WP-CLI implmementation current on the platform? 

Off the top of my head, it should be a lot like (exactly like?) our process for keeping Drush updated.

**Comment by danielbachhuber** [comment]
> Off the top of my head, it should be a lot like (exactly like?) our process for keeping Drush updated.

@greg-1-anderson Is this documented somewhere I can review?

**Comment by danielbachhuber** [comment]
I see what y'all are talking about w/r/t building a custom Phar right now. Seems hacky :) 

I'd recommend using the WP-CLI stable phar: https://github.com/wp-cli/builds/blob/gh-pages/phar/wp-cli.phar

wp_launch_check can be deployed separately, and loaded with a `require` statement in a global `config.yml`: http://wp-cli.org/config/

**Comment by danielbachhuber** [comment]
Oh, and because the build is currently being generated from a `git clone`, you're not necessarily using a "stable" version of WP-CLI — you're using whatever is on master at the time of the clone. Glad I haven't broken anything for you :)

**Comment by danielbachhuber** [comment]
Closing in favor of #37
