### ISSUE TITLE
Switch to tag-based deploys

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/wp_launch_check#37]
It would be ideal to switch to tag-based deploys so that we can use a consistent milestone-based development strategy.

- [x] Remove auto-deploy from wp launch check
- [ ] ~~switch wp launch check to compile its own Phar, and only build a rpm on tagged releases~~
- [ ] switch Pantheon Chef to use WP-CLI stable Phar, instead of building its own Phar
* [ ] switch Pantheon Chef to use WP Launch Check stable Phar
* [ ] Specify stable WP-CLI and WP Launch Check versions in Chef cookbook, which the receipt references
- [ ] ~~have Pantheon load wp launch check Phar from `WP_CLI_CONFIG_PATH` environment variable that references a `config.yml~~
- [ ] Modify the Pantheon wrapper script `wp --require=/opt/wp-launch-check/wp-launch-check.phar`

**Comment by greg-1-anderson** [comment]
I should test #40 so that we can merge it.

**Comment by greg-1-anderson** [comment]
@joemiller Please review the above -- we edited the summary to reflect our new strategy.

**Comment by danielbachhuber** [comment]
🚢 🚢
