### ISSUE TITLE
When Running a Site Network - check the domains for the env vs domains in WP

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/wp_launch_check#43]
We should surface a warning if the lists of domains are out of sync.

**Comment by danielbachhuber** [comment]
To get started on this, we'd need details on how to pull the domain list from the Pantheon API.

**Comment by danielbachhuber** [comment]
Actually, this may already be present in the omnibus call.

**Comment by nstielau** [comment]
This is the best path for getting hostnames:
https://github.com/pantheon-systems/terminus/blob/7a8daead82edac02e5c7ade014c4edb911044f89/php/Terminus/Models/Collections/Hostnames.php#L20

On Mon, Feb 22, 2016 at 3:28 PM, Daniel Bachhuber <notifications@github.com>
wrote:

> Actually, this may already be present in the omnibus call.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pantheon-systems/wp_launch_check/issues/43#issuecomment-187391004>
> .
>



-- 
Nick Stielau | p 415-515-2120
Director of Engineering | Pantheon
