### ISSUE TITLE
Verify domain warnings work as expected on the Pantheon environment

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/wp_launch_check#61]
> When it gets closer to releasing v0.7.0, we'll want to do some sanity checking of this feature on the Pantheon environment, given I'm mocking the omnibus call.

From https://github.com/pantheon-systems/wp_launch_check/pull/59#issuecomment-217186558

**Comment by ccharlton** [comment]
Still a valid ticket?

**Comment by danielbachhuber** [comment]
@ccharlton We can punt on this — it's long past.
