### ISSUE TITLE
Show current WordPress version

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/wp_launch_check#64]
A trivial check, but a nice one to be able to bubble up. We should report the current WordPress version along with whether or not there's an update available.

@stevector can you work with @danielbachhuber to figure out whether this should be a net new check or if we can simply add it to the output of the "Is your WP Core up to date?" check?

**Comment by stevector** [comment]
@danielbachhuber Do you have thoughts on how this check gets implemented?

**Comment by danielbachhuber** [comment]
Given we already have `Pantheon\Checks\General->checkPluginCount()`, I think it would make sense to include this check on the `Pantheon\Checks\General` class.

We could use [these doctor tests](https://github.com/runcommand/doctor/blob/master/features/diagnose-core-update.feature) as the basis for the reporting.
