### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/cron.php on line 58

### ISSUE THREAD

**Issue by dustinleblanc** [pantheon-systems/wp_launch_check#65]
Can confirm both a customer is seeing this and I can replicate on a vanilla site

**Comment by danielbachhuber** [comment]
@dustinleblanc This error implies the `cron` option is empty on the site. Did you just see this on a brand new install (which is probably acceptable), or have you seen this on an existing site too?

**Comment by danielbachhuber** [comment]
And, just to take a step back, I'm not 100% confident on what we should be telling the end user when their `cron` option is empty. If `cron` is unintentionally empty on a live site, then it's a problem in its own right, and may also be a symptom of a larger problem.

**Comment by audvin** [comment]
Anything that a customer can do to avoid these PHP Notices? I'm getting two notices on our Live instance, see the two screenshots from Bugsnag:

<img width="1380" alt="Screen Shot 2019-05-10 at 2 13 24 PM" src="https://user-images.githubusercontent.com/1017880/57559987-2e61c400-7339-11e9-97d7-396a4001e619.png">

And...

<img width="1374" alt="Screen Shot 2019-05-10 at 2 13 12 PM" src="https://user-images.githubusercontent.com/1017880/57559988-2efa5a80-7339-11e9-990b-7d20cafdc746.png">

**Comment by danielbachhuber** [comment]
@audvin Want to submit a pull request? I think we should be able to deploy minor fixes like this.

**Comment by audvin** [comment]
Thanks @danielbachhuber 🎉
