### ISSUE TITLE
Plugin is most recent version; says it needs an update.

### ISSUE THREAD

**Issue by jamidwyer** [pantheon-systems/wp_launch_check#68]
After running Launch Check on a WordPress multidev site, I see:

```
Plugin                                          Current Available   Needs Update      Vulnerabilities
advanced-custom-fields-pro  5.4.5   5.4.5   1                     None
```

Any ideas on what change will get that Needs Update to 0?

**Comment by ccharlton** [comment]
Still an issue?

**Comment by jazzsequence** [comment]
We have passing behat tests for this behavior, so I don't think this is an issue anymore.
