### ISSUE TITLE
Cron check should alert if too many tasks are scheduled two close together

### ISSUE THREAD

**Issue by mikevanwinkle** [pantheon-systems/wp_launch_check#7]
Sometimes badly coded plugins can lead to dozens of instances of the same task to be scheduled at the same time or within seconds of each other. This check should look for a pattern and alert if it exists.

https://github.com/pantheon-systems/wp_launch_check/edit/master/CHECKS.md#71

**Comment by danielbachhuber** [comment]
We're going to use 10 as a magic number. If there are 10 or greater of similar jobs, then we'll throw some warning.
