### ISSUE TITLE
Error: objectcache is not a registered subcommand

### ISSUE THREAD

**Issue by thomas-thackery** [pantheon-systems/wp_launch_check#79]
### Summary
Running `wp launchcheck objectcache` results in error. 

### Actual result
```
Error: 'objectcache' is not a registered subcommand of 'launchcheck'. See 'wp help launchcheck'.
 [notice] Command: <site>.<env> -- 'wp launchcheck objectcache' [Exit: 1]
 [error]
```

### Steps To Reproduce
Run `terminus remote:wp <site>.<env> launchcheck objectcache`
Change the environment resulted in same error.

**Comment by stevector** [comment]
Hi @kveldalf. I think this issue is simply an error in the readme. The command is `object_cache`, not `objectcache`. I've open https://github.com/pantheon-systems/wp_launch_check/issues/80
