### ISSUE TITLE
Unable to install plugin package

### ISSUE THREAD

**Issue by jhabdas** [pantheon-systems/wp_launch_check#82]
**Steps to reproduce**

```
wp cli update
wp package install pantheon-systems/wp_launch_check
```

**Actual result**

```
Installing package pantheon-systems/wp_launch_check (dev-master)
Updating /Users/jhabdas/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1105920 bytes) in phar:///usr/local/bin/wp/vendor/composer/composer/src/Composer/Cache.php on line 92
```

**Expected result**

Installation

**Environment**

Darwin 16.6.0
WP-CLI 1.2.1
Composer version 1.4.2 2017-05-17 08:17:52

**Comment by danielbachhuber** [comment]
Hi @jhabdas,

Please see https://make.wordpress.org/cli/handbook/common-issues/#php-fatal-error-allowed-memory-size-of-999999-bytes-exhausted-tried-to-allocate-99-bytes

**Comment by jhabdas** [comment]
Thanks @danielbachhuber. Will do.

**Comment by jhabdas** [comment]
fyi - https://github.com/torifat/yarn/tree/feature/packagist

**Comment by jhabdas** [comment]
I could serve 7000 users with 512MB ran and a Redis object cache. Composer is gross.

**Comment by jhabdas** [comment]
Anyway the memory bump fixed the 'poser install issue. Thanks again. ::sets memory back to 128M::
