### ISSUE TITLE
Status check shows "black" for object cache on site with nested docroot

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/wp_launch_check#83]
Steps to reproduce:
Serve WordPress from a nested docroot as specified in https://pantheon.io/docs/nested-docroot/

Check "Status" on Pantheon dashboard:

![image](https://user-images.githubusercontent.com/7874556/30339663-a3ef2e6e-97a4-11e7-893d-b9ec9924eb0c.png)

ref. BUGS-1470

**Comment by danielbachhuber** [comment]
@ari-gold Identified and addressed the issue in #84

Core checks for `WP_CONTENT_DIR . '/object-cache.php'`. We've been erroneously checking `ABSPATH . '/wp-content/object-cache.php'`, which is invalid when WP is installed in a nested docroot.

**Comment by danielbachhuber** [comment]
🔨

**Comment by tinefin** [comment]
Still not working on Dashboard. 
Ref: BUGS-1524

**Comment by danielbachhuber** [comment]
@tinefin To clarify, this has been fixed but hasn't yet been deployed to production. It's currently a part of a [v0.7.0](https://github.com/pantheon-systems/wp_launch_check/milestone/2) release that needs product attention before it goes it. I believe @greg-1-anderson filed a ticket but I don't know the number.

**Comment by greg-1-anderson** [comment]
The card is https://getpantheon.atlassian.net/browse/BUGS-1524

I'll prepare a PR today & probably deploy on Monday.
