### ISSUE TITLE
Clarification on cron errors

### ISSUE THREAD

**Issue by sarahg** [pantheon-systems/wp_launch_check#85]
In the Dashboard Status check for a Dev environment, we're seeing a cron job marked with the red "error" status:

![image](https://user-images.githubusercontent.com/667501/43491239-5e8e95e2-94e9-11e8-8d2c-91adb1d86e6f.png)

The other jobs on the list are also Past Due, but they do not include the error class on the table row. I see the same result with running the check with wp-cli directly.

Is there some meaning to what we're seeing here, or is it possibly a bug with the cron checks?

Case: #110454

**Comment by sarahg** [comment]
Hey @danielbachhuber, thanks for taking a look! Agreed that this is a weird one, the code seems pretty straightforward here. 

Here's the HTML for the table: https://gist.github.com/sarahg/c6453ef5153d925ed81e252165e90abb.

This site is running PHP 7.1, and WP core is up-to-date.

**Comment by danielbachhuber** [comment]
@sarahg Odd! Can you grant me access to a multi-dev environment that reproduces the error, and I'll debug further based on live data?

**Comment by sarahg** [comment]
Nice find! Thanks for investigating, @danielbachhuber.
