### ISSUE TITLE
Detect suspicious folders in the plugins folder

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/wp_launch_check#88]
Would it be a good addition if launch check can detect suspicious folders inside the plugins folder?

<img width="1165" alt="2018-11-03_0920" src="https://user-images.githubusercontent.com/5098765/47946694-1ce2ce00-df4a-11e8-9c9b-134a643a3630.png">

In this installation, there is a folder names vslider_ which contains malicious code which is not listed in the WP admin dashboard and plugin is listed

**Comment by ccharlton** [comment]
Is `vslider_` a known WP bad folder? Or is there a more detailed signature that can be used to detect versus a static folder name (string)? I ask because what if the script made a different folder name (`vslider2021_`) to get past detection?

**Comment by jazzsequence** [comment]
As much as I like the idea of checking for potentially malicious folders, there's no way to validate what's "safe" and what's "suspicious". Even a potentially "safe"-looking folder (say `woocommerce/`) might be spoofed by a malicious script. 

Closing as `wontdo`.  The checker is already looking for potentially risky files by evaluating for `eval` and `base64_decode`.
