### ISSUE TITLE
wpvulndb.com API endpoint returns 404 error

### ISSUE THREAD

**Issue by cwoods96** [pantheon-systems/wp_launch_check#89]
We have recently started receiving the errors below when running with plugin option.

Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81 Warning: file_get_contents(https://wpvulndb.com/data/plugin_vulns.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 80 Warning: Invalid argument supplied for foreach() in phar:///opt/pantheon/wp-launch-check-0.x/wp-launch-check.phar/php/pantheon/checks/plugins.php on line 81

**Comment by danielbachhuber** [comment]
It looks like that API endpoint disappeared. The API now requires some authentication token: https://wpvulndb.com/api

Thanks for bring this up. I'm not sure how quickly we can resolve this but I'll flag it upstream.

**Comment by dylanjharris** [comment]
Any progress on this? I'm encountering the issue with Performance Medium, WP 5.0.2, PHP 7.2.13. If more info is helpful let me know - looks like you have a handle on it but there's been no progress in 26 days. Please advise, thanks!

**Comment by danielbachhuber** [comment]
@dylanjharris No progress at this point. We'll need to decide whether we want to continue to support the feature (and pay for the API) or remove the feature entirely. I don't think we'll move forward on this until well into Q1 at the earliest.

**Comment by TheLastCicada** [comment]
I believe this causes the Pantheon database to display inaccurate information about plugin vulnerabilities on the site.  I would suggest Pantheon remove any claim of scanning a site for vulnerabilities if it is known that this scan isn't actually working.  This has already caused an embarrassing situation for a client I work with on Pantheon.

**Comment by ari-gold** [comment]
Thanks for reporting this issue. We're now tracking at Pantheon internally as BUGS-2506 and will prioritize a fix.

Unfortunately, this issue queue isn't being actively monitored, so in the future, please contact Pantheon support to report bugs like this one.

**Comment by ari-gold** [comment]
@cwoods96  @dylanjharris  @TheLastCicada  A fix has been deployed and the Pantheon site dashboard "Status" tab for WordPress sites now accurately reports plugin vulnerabilities.
