### ISSUE TITLE
Plugin update status cached is status check results

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/wp_launch_check#96]
I believe the faulty logic lies in https://github.com/pantheon-systems/wp_launch_check/blob/master/php/pantheon/checks/plugins.php#L38

I _think_ `get_plugin_updates` is provided by WP-CLI, or was in the past, but perhaps no more?

@danielbachhuber can you shed any light here?

**Comment by ataylorme** [comment]
Ah, it is a [WordPress core function](https://developer.wordpress.org/reference/functions/get_plugin_updates/)

**Comment by danielbachhuber** [comment]
@ataylorme How do I reproduce the bug?

**Comment by ataylorme** [comment]
And the function results are cached in a transient. Running a [core update check](https://developer.wordpress.org/cli/commands/core/check-update/) before the status check yields the proper results.

Perhaps we should force a core update check as part of the status check process?

**Comment by ataylorme** [comment]
@danielbachhuber I think I sorted out the cause. To reproduce:

1. Create a new multidev environment
1. Set it to SFTP mode
1. Use wp-cli to install an out of date plugin (e.g. `terminus wp site.env -- plugin install akismet --version=3.1.3 --force`)
1. Run the status check

**Comment by danielbachhuber** [comment]
> And the function results are cached in a transient. Running a [core update check](https://developer.wordpress.org/cli/commands/core/check-update/) before the status check yields the proper results.
> 
> Perhaps we should force a core update check as part of the status check process?

Do you mean plugin update check?

WP-CLI forces an upgrade refresh for `wp plugin list` for exactly this reason:
* https://github.com/wp-cli/extension-command/blob/07bd9d22b726a8277a22ca7ae3cd06a9d3b22356/src/WP_CLI/CommandWithUpgrade.php#L465-L466
* https://github.com/wp-cli/extension-command/blob/07bd9d22b726a8277a22ca7ae3cd06a9d3b22356/src/Plugin_Command.php#L44

**Comment by ataylorme** [comment]
> Do you mean plugin update check?
Yes.

@danielbachhuber should we get plugin version information from WP-CLI rather than the core `get_plugin_updates` function?

If not, a similar forced upgrade refresh seems like the way to go.

**Comment by danielbachhuber** [comment]
> should we get plugin version information from WP-CLI rather than the core `get_plugin_updates` function?

No need, I don't think. `get_plugin_updates` should be fine.

**Comment by ccharlton** [comment]
Still an issue?
